{
	"Password": "<Password from config>",
	"Artist": "{{artist}}",
	"Title": " {{title}}",
	"Comments": "{{comments}}",
	"Album": "{{album}}",
	"Genre": "{{genre}}",
	"Year": "{{year}}",
	"Duration": "{{duration}}",
	"OutCue": "{{outcue}}",
	"Tags": "{{tags}}",
	"Disabled": "{{disabled}}",
	"Segue": "{{segue}}",
	"Path": "{{path}}",
	"Type": "{{type}}",
	"Intro": "{{intro}}",
	"CueIn": "{{cueIn}}",
	"CueOut": "{{cueOut}}",
	"Added": "{{added}}",
	"Sweeper": "{{sweeper}}",
	"NoFade": "{{nofade}}",
	"ValidFrom": "{{validfrom}}",
	"Expires": "{{expires}}",
	"Guid": "{{guid}}",
	"StationID": "1"
}